#!/usr/bin/env python3
"""
Train XGBoost models for doc-quality scoring.

Reads a single features.csv from training/ directory (generated by extract-features.mjs),
trains one model per mode (fast/thorough) with preset as a feature, and outputs a JSON
model bundle to models/quality-models.json.

Usage:
    pip install -r scripts/requirements.txt
    python scripts/train-model.py
    python scripts/train-model.py --input-dir ./training --output ./models/quality-models.json
"""

import argparse
import json
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score
from xgboost import XGBRegressor


# Feature names matching src/features.ts
FAST_FEATURES = [
    'megapixels', 'width', 'height', 'aspectRatio', 'fileSize',
    'bpp', 'brightnessAvg', 'brightnessStdevMax',
    'laplacianStdev', 'laplacianMean', 'laplacianVariance', 'edgeRatio',
    'dpi', 'isJpeg', 'presetIdx',
]

ALL_FEATURES = FAST_FEATURES + [
    'foregroundRatio',
    'sharpnessRatioTopBot', 'brightnessDiffTopBot',
    'shadowEdgeCenterDiff', 'centerBrightness', 'edgeBrightness',
    'backgroundP90', 'skewAngle', 'colorSaturation',
    'fftHighFreqRatio', 'fftSpectralPeaks', 'fftJpegBlockiness',
    'zoneBrightnessDiff', 'zoneSharpnessRatio', 'directionalEnergyRatio',
    'zoneBrightness0', 'zoneBrightness1', 'zoneBrightness2', 'zoneBrightness3',
    'zoneSharpness0', 'zoneSharpness1', 'zoneSharpness2', 'zoneSharpness3',
    'channelCount',
]

PREFLIGHT_FEATURES = [
    'megapixels', 'fileSize', 'brightnessAvg', 'brightnessStdevMax',
    'laplacianStdev', 'edgeRatio', 'foregroundRatio', 'blankStdevMax',
]


def tree_to_json(tree, node_id=0):
    """Convert a single XGBoost tree to nested JSON format."""
    tree_df = tree
    node = tree_df[tree_df['Node'] == node_id].iloc[0]

    if node['Feature'] == 'Leaf':
        return {'leaf': float(node['Gain'])}

    result = {
        'split': int(node['Feature'].replace('f', '')),
        'split_condition': float(node['Split']),
        'missing': 1 if int(node['Yes']) == int(node['Missing']) else 0,
        'left': tree_to_json(tree_df, int(node['Yes'])),
        'right': tree_to_json(tree_df, int(node['No'])),
    }
    return result


def model_to_json(model, feature_names):
    """Convert an XGBoost model to our JSON format."""
    booster = model.get_booster()
    trees_df = booster.trees_to_dataframe()

    tree_ids = trees_df['Tree'].unique()
    trees = []
    for tid in sorted(tree_ids):
        tree_data = trees_df[trees_df['Tree'] == tid].copy()
        # Extract node IDs from the ID column (format: "0-0", "0-1", etc.)
        tree_data['Node'] = tree_data['ID'].apply(lambda x: int(x.split('-')[1]))
        trees.append([tree_to_json(tree_data)])

    return {
        'trees': trees,
        'base_score': float(model.get_params().get('base_score', 0.5)),
        'objective': 'reg:squarederror',
        'feature_names': feature_names,
    }


def train_model(df, feature_cols, label_col='label', name='model'):
    """Train a single XGBoost model and return it with metrics."""
    X = df[feature_cols].copy()
    y = df[label_col]

    # Replace empty strings and inf with NaN (XGBoost handles NaN natively)
    X = X.replace([np.inf, -np.inf, ''], np.nan).astype(float)

    model = XGBRegressor(
        objective='reg:squarederror',
        n_estimators=100,
        max_depth=4,
        learning_rate=0.1,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
    )

    # Cross-validate
    if len(X) >= 5:
        cv_folds = min(5, len(X))
        scores = cross_val_score(model, X, y, cv=cv_folds, scoring='r2')
        print(f"  {name}: CV R² = {scores.mean():.3f} ± {scores.std():.3f} (n={len(X)})")
    else:
        print(f"  {name}: Too few samples for CV (n={len(X)}), training on all data")

    # Train on all data
    model.fit(X, y)

    # Feature importance
    importances = model.feature_importances_
    top_features = sorted(
        zip(feature_cols, importances),
        key=lambda x: x[1],
        reverse=True,
    )[:10]
    print(f"    Top features: {', '.join(f'{n}={v:.3f}' for n, v in top_features)}")

    return model


def main():
    parser = argparse.ArgumentParser(description='Train doc-quality XGBoost models')
    parser.add_argument('--input-dir', default='training', help='Directory with CSV files')
    parser.add_argument('--output', default='models/quality-models.json', help='Output model bundle')
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    bundle = {}

    # Single unified CSV — preset is feature #14 (presetIdx), not a separate model
    csv_path = input_dir / 'features.csv'
    if not csv_path.exists():
        # Fallback: try legacy per-preset CSVs and combine
        legacy_dfs = []
        for preset in ['document', 'receipt', 'card']:
            p = input_dir / f'{preset}-features.csv'
            if p.exists():
                legacy_dfs.append(pd.read_csv(p))
        if legacy_dfs:
            df = pd.concat(legacy_dfs, ignore_index=True)
            print(f"Combined {len(legacy_dfs)} legacy CSVs: {len(df)} total rows")
        else:
            print(f"No CSV found at {csv_path}")
            sys.exit(1)
    else:
        df = pd.read_csv(csv_path)
        print(f"Loaded {len(df)} rows from {csv_path}")

    # One model per mode (fast/thorough) — preset is just a feature
    fast_df = df[df['mode'] == 'fast']
    if len(fast_df) > 0:
        model = train_model(fast_df, FAST_FEATURES, name='fast')
        bundle['fast'] = model_to_json(model, FAST_FEATURES)

    thorough_df = df[df['mode'] == 'thorough']
    if len(thorough_df) > 0:
        model = train_model(thorough_df, ALL_FEATURES, name='thorough')
        bundle['thorough'] = model_to_json(model, ALL_FEATURES)

    # Preflight model (uses fast-mode rows with subset of features)
    if len(fast_df) > 0:
        available_cols = [c for c in PREFLIGHT_FEATURES if c in fast_df.columns]
        if len(available_cols) >= 3:
            model = train_model(fast_df, available_cols, name='preflight')
            bundle['preflight'] = model_to_json(model, available_cols)

    if not bundle:
        print("\nNo models trained! Ensure features.csv exists in the input directory.")
        sys.exit(1)

    # Write bundle
    with open(output_path, 'w') as f:
        json.dump(bundle, f, indent=2)
    print(f"\nWrote {len(bundle)} models to {output_path}")
    print(f"Models: {', '.join(sorted(bundle.keys()))}")


if __name__ == '__main__':
    main()
